### ISSUE TITLE
Create a public profile

### ISSUE THREAD

**Issue by srosset81** [activitypods/mastopod#3]
Allow to create a public profile, in addition to the private profile, so that we have something to show to Mastodon users.

**Comment by srosset81** [comment]
The main question is: does Mastodon look for profiles defined with the `url` predicate ? And if it does, would it support two profiles, one private (that is cannot access) and another one public ? If it does, this would be the best solution. Otherwise we would need to put the picture and other information in the WebID. In either case, we need to have a good UI/UX in order to not lose users.

Some links and comments:

https://docs.joinmastodon.org/spec/activitypub/#properties-used-1
The `as:url` predicate is supported but we don't know if it can link to a `as:Profile` object or if it's just a link.

From Damon:

Friendica and Hubzilla allow multiple identities (they call this "channels")
https://hubzilla.org/help/member/member_guide#Channel_Permission_Roles

How this premium account operates:
https://documenter.getpostman.com/view/25748250/2sAXjJ6Yfe 

for Mastopod the private account would/should default to follower-only, https://docs.joinmastodon.org/user/posting/#:~:text=To%20effectively%20publish%20private%20(followers,make%20past%20public%20posts%20private.

Another service to take a look at their docs is GoToSocial, they focus a lot of user privacy control https://docs.gotosocial.org/en/latest/user_guide/settings/#default-interaction-policies

**Comment by outlaw-dame** [comment]
Adding this is this is a significant part of what makes Nomadic Identity work https://socialhub.activitypub.rocks/t/fep-61cf-the-openwebauth-protocol/3907
https://indieweb.org/OpenWebAuth

**Comment by srosset81** [comment]
> The main question is: does Mastodon look for profiles defined with the url predicate ? And if it does, would it support two profiles, one private (that is cannot access) and another one public ?

I set a mypod.store profile as public, and it doesn't appear in Mastodon clients. If you fetch a Mastodon user, the `url` property will point to the user's page (which is different from the actor URI in Mastodon).

So the public profile will be the one that is attached to the WebID...

**Comment by outlaw-dame** [comment]
This may also shed light and clarify on the issue and Mastodon’s use https://socialhub.activitypub.rocks/t/fep-2c59-discovery-of-a-webfinger-address-from-an-activitypub-actor/3813/7
